name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: update build env
      run: sudo apt-get update --fix-missing -y
    - name: install prerequisities
      run: sudo apt-get install libcups2-dev python3-dev gcc python3-setuptools
    - name: make
      run: make
    - name: sudo make install
      run: sudo make install
    - name: make dist
      run: make dist
    - name: install cups and ippeveprinter for testing
      run: sudo apt-get install cups cups-ipp-utils
    - name: start cupsd - needed for testing
      run: sudo systemctl start cups
    - name: start ippeveprinter to simulate a driverless printer
      run: mkdir -p /tmp/ippeve/spool/ && ippeveprinter -vvvv -s 10,0 -d "/tmp/ippeve/spool/" -k "test-ippeve" &
    - name: install a permanent queue
      run: sudo lpadmin -p test-permanent -v ipp://localhost:8000/ipp/print -m everywhere -E && sleep 5
    - name: python3 test.py
      run: python3 test.py
